# Generated by Django 5.0.6 on 2024-07-03 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Edital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                ("data_pregao", models.DateField()),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editais.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Editais",
            },
        ),
        migrations.CreateModel(
            name="Preco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.CharField(max_length=50)),
                ("preco_minimo", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editais.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.IntegerField(max_length=3)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "unidade",
                    models.CharField(
                        blank=True,
                        choices=[("un", "un"), ("kg", "kg"), ("g", "g")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("gramatura", models.CharField(max_length=10)),
                (
                    "valor_referencia",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "valor_arrematado",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "margem",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "colocacao",
                    models.CharField(
                        blank=True,
                        choices=[("1", "1º"), ("2", "2º"), ("3", "3º"), ("4", "< 4º")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("ganhador", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("obs", models.CharField(max_length=200)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="editais.edital"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="editais.produto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Itens",
            },
        ),
    ]
