# Generated by Django 5.0.6 on 2024-07-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="margem",
            new_name="dif",
        ),
        migrations.AlterField(
            model_name="item",
            name="item",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="unidade",
            field=models.CharField(
                choices=[("un", "un"), ("kg", "kg"), ("g", "g")],
                default=12,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="valor_arrematado",
            field=models.DecimalField(decimal_places=3, default=12, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="valor_minimo",
            field=models.DecimalField(decimal_places=3, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="valor_referencia",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
